from database import db

class Teilnehmer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    alter = db.Column(db.Integer)
    berufserfahrung = db.Column(db.Integer)
    geschlecht = db.Column(db.String(20))
    schulstufe = db.Column(db.String(50))
    funktionen = db.Column(db.String(100))

    # Spalten für alle 21 Fragen
    frage1 = db.Column(db.Integer)
    frage2 = db.Column(db.Integer)
    frage3 = db.Column(db.Integer)
    frage4 = db.Column(db.Integer)
    frage5 = db.Column(db.Integer)
    frage6 = db.Column(db.Integer)
    frage7 = db.Column(db.Integer)
    frage8 = db.Column(db.Integer)
    frage9 = db.Column(db.Integer)
    frage10 = db.Column(db.Integer)
    frage11 = db.Column(db.Integer)
    frage12 = db.Column(db.Integer)
    frage13 = db.Column(db.Integer)
    frage14 = db.Column(db.Integer)
    frage15 = db.Column(db.Integer)
    frage16 = db.Column(db.Integer)
    frage17 = db.Column(db.Integer)
    frage18 = db.Column(db.Integer)
    frage19 = db.Column(db.Integer)
    frage20 = db.Column(db.Integer)
    frage21 = db.Column(db.Integer)